language: node_js
node_js:
  - "11"
cache:
  directories:
    - $HOME/.npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    node: "11"
    branch: master
